# Generated by Django 6.0.1 on 2026-01-17 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jerseys', '0001_initial'),
    ]

    operations = [
    ]
