# Generated by Django 6.0.1 on 2026-01-17 21:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jerseys', '0002_auto_20260117_2045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jersey',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='jersey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jersey',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='jersey',
            unique_together={('team', 'size', 'type', 'brand')},
        ),
    ]
