# Generated by Django 6.0.1 on 2026-01-23 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jerseys', '0003_alter_jersey_id_alter_team_id'),
        ('jerseys', '0003_alter_jersey_options_jersey_created_at_and_more'),
    ]

    operations = [
    ]
