# Generated by Django 6.0.1 on 2026-01-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jerseys', '0004_merge_20260123_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jersey',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
