# Generated by Django 6.0.1 on 2026-01-24 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jerseys', '0004_merge_20260119_1447'),
        ('jerseys', '0005_alter_jersey_id_alter_team_id'),
    ]

    operations = [
    ]
