# Generated by Django 4.2 on 2026-01-17 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jerseys', '0003_alter_jersey_id_alter_team_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2)),
                ('brand', models.CharField(choices=[('Nike', 'Nike'), ('Adidas', 'Adidas'), ('Puma', 'Puma'), ('Under Armour', 'Under Armour'), ('New Balance', 'New Balance'), ('Other', 'Other')], max_length=50)),
                ('type', models.CharField(choices=[('Home', 'Home'), ('Away', 'Away'), ('Third', 'Third'), ('Goalkeeper', 'Goalkeeper'), ('Training', 'Training'), ('Other', 'Other')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_retro', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='jersey_images/')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jerseys.team')),
            ],
        ),
    ]
