# Generated by Django 4.2 on 2026-01-18 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_post_is_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='stock',
        ),
    ]
